### ISSUE TITLE
Extension no longer works

### ISSUE THREAD

**Issue by swarajban** [auth0-extensions/auth0-logs-to-sumologic#16]
The auth0-logs-to-sumologic extension no longer posts logs to Sumo Logic. I have tried uninstalling and reinstalling the extension, but no logs are being posted to Sumo Logic. Can you please help us resolve?

**Comment by fyockm** [comment]
@swarajban what version of the extension are you using? are you getting any errors?
by "no longer posts logs to Sumo Logic", do you mean the extension was working prior and recently stopped?

**Comment by swarajban** [comment]
@fyockm :
* The auth0 extensions dashboard does not show which version is being used. That said, I just removed my previous installation, and reinstalled the latest `Auth0 Logs to Sumo Logic` extension from the extensions page: [https://manage.auth0.com/#/extensions](https://manage.auth0.com/#/extensions)
* It looks like the extension uses the (currently in Beta) 'Scheduled jobs' feature here: [https://manage.auth0.com/#/cron](https://manage.auth0.com/#/cron). The scheduled cron job shows no errors (see image below)
* Using the slack extension w/ `SLACK_SEND_SUCCESS` set to true, the cron runs every 5 minutes and says 0 logs were processed (see image below)
* The extension used to work correctly: I see some older Auth0 logs in Sumo Logic


Cron job successes:
![image](https://user-images.githubusercontent.com/384283/38207347-4bb86078-3662-11e8-9a4c-20065d0cb2ae.png)

Slack runs
![image](https://user-images.githubusercontent.com/384283/38207382-74eb91c2-3662-11e8-90e8-f0abc1c0d00d.png)

**Comment by swarajban** [comment]
Anything? I just had to write & deploy my own service that handles sending Auth0 logs to Sumo Logic because I cannot wait any longer. 

If anyone else has issues, happy to share our solution

**Comment by fyockm** [comment]
@swarajban we just published v2.0.4, which should fix the issue you were seeing
