### ISSUE TITLE
When cron job fails logging starts from the first available log.

### ISSUE THREAD

**Issue by saltukalakus** [auth0-extensions/auth0-logs-to-sumologic#2]
When cron job fails, due to that last log id is lost, logging starts from the first available log which cause redundant logging of the same logs. Related P1 ticket ZD - 21970

I can think of 3 possible solutions;

* Enabling persistent storage with an external DB for last log Id and updating it for each transfer to Sumologic.
* Getting the last log sent to Sumologic with Sumologic search API and continuing from that point.
* We are already creating a client in dashboard for the Sumologic logger. We can store the last log id in Application Metadata with [management v2 API](https://auth0.com/docs/api/management/v2#!/Clients/get_clients_by_id) using `client_metadata`attribute.

**Comment by francocorreasosa** [comment]
*Update:* 
The module is using Webtask Storage to store the last log ID along with the total logs processed per batch in a format like this:
```js
{ data: 
   { checkpointId: '49560429270835143462024371459481208727380490192961929218',
     totalLogsProcessed: 12 },
  etag: 1300 }
```
I have not been able to reproduce the bug so far.

**Comment by saltukalakus** [comment]
P1, ZD-22612, in log extensions as Log Id should always increment, can we add a logic to check if the new logs coming from log API has a bigger log id then the one we set in 'from' attribute. This logic may help to prevent the old log redelivery. And if we notice such a log id, where response is older logs, we can report it internally to crew-2 for a review.
